version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "5002:5002"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: UyNh4eve@6514
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
